---
# tasks file for java

- include: debian.yml
  when:
    ansible_distribution == 'Debian' or
    ansible_distribution == 'Ubuntu'

- include: redhat.yml
  when:
    ansible_distribution == 'Red Hat Enterprise Linux' or
    ansible_distribution == 'CentOS'
